# Generated by Django 3.2.13 on 2022-06-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_upload', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('C', 'Cloths'), ('A', 'Accessories')], max_length=1)),
                ('sexe', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('M/W', 'Mixte')], max_length=3)),
                ('types', models.CharField(choices=[('C', 'Cloths'), ('A', 'Accessories')], max_length=1)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricamo.design')),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricamo.product')),
            ],
        ),
    ]
