# Generated by Django 3.2.13 on 2022-06-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('H', 'Hoodie'), ('S', 'Sweater'), ('E', 'Ensemble'), ('B', 'Bag')], max_length=1),
        ),
    ]
