# Generated by Django 3.2.13 on 2022-07-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('C', 'Cloth'), ('A', 'Accessorie')], max_length=1),
        ),
    ]
