# Generated by Django 3.2.13 on 2022-07-01 00:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0004_auto_20220701_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('adresse', models.TextField(max_length=100)),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('optionel', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
