# Generated by Django 3.2.13 on 2022-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product-images-display/'),
        ),
    ]
