# Generated by Django 3.2.13 on 2022-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0007_auto_20220701_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
