# Generated by Django 3.2.13 on 2022-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hoodie', 'Hoodie'), ('S', 'Sweater'), ('E', 'Ensemble'), ('B', 'Bag')], max_length=8),
        ),
    ]
