# Generated by Django 3.2.13 on 2022-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0012_auto_20220701_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
