# Generated by Django 3.2.13 on 2022-07-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0019_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=7, null=True),
        ),
    ]
