# Generated by Django 3.2.13 on 2022-07-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0020_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ricamo.product'),
        ),
        migrations.AddField(
            model_name='commande',
            name='size',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='standart_size',
            field=models.IntegerField(default=0),
        ),
    ]
