# Generated by Django 3.2.13 on 2022-07-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0021_auto_20220711_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ricamo.product'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
