# Generated by Django 3.2.13 on 2022-07-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0022_auto_20220711_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ville',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='wilaya',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
