# Generated by Django 3.2.13 on 2022-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0024_commande_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
