# Generated by Django 3.2.13 on 2022-07-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0025_alter_commande_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='order_date',
            new_name='date',
        ),
    ]
