# Generated by Django 3.2.13 on 2022-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0029_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
