# Generated by Django 3.2.13 on 2022-07-12 14:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0030_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ'),
        ),
    ]
