# Generated by Django 3.2.13 on 2022-07-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0032_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
