# Generated by Django 3.2.13 on 2022-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0033_product_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=400)),
            ],
        ),
    ]
