# Generated by Django 3.2.13 on 2022-07-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0037_auto_20220714_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
