# Generated by Django 3.2.13 on 2022-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0039_auto_20220714_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
