# Generated by Django 3.2.13 on 2022-12-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0042_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hoodie', 'Hoodie'), ('Sweater', 'Sweater'), ('Ensemble', 'Ensemble'), ('Bag', 'Bag'), ('T-Shirt', 'T-Shirt')], default='Sweater', max_length=8, null=True),
        ),
    ]
