# Generated by Django 3.2.13 on 2022-12-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0046_alter_design_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
