# Generated by Django 3.2.13 on 2022-12-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0048_auto_20221219_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
