# Generated by Django 3.2.13 on 2022-12-20 15:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0049_auto_20221219_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1152, 1536], upload_to='category-images-display/'),
        ),
    ]
