# Generated by Django 3.2.13 on 2022-12-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0054_auto_20221220_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='l_size',
        ),
        migrations.RemoveField(
            model_name='color',
            name='m_size',
        ),
        migrations.RemoveField(
            model_name='color',
            name='s_size',
        ),
        migrations.RemoveField(
            model_name='color',
            name='standart_size',
        ),
        migrations.RemoveField(
            model_name='color',
            name='xl_size',
        ),
        migrations.RemoveField(
            model_name='color',
            name='xxl_size',
        ),
    ]
