# Generated by Django 3.2.13 on 2022-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0059_auto_20221222_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
