# Generated by Django 3.2.13 on 2022-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0060_alter_commande_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='domicile',
            field=models.BooleanField(default=False),
        ),
    ]
