# Generated by Django 3.2.13 on 2022-12-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0061_commande_domicile'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricamo.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ricamo.product')),
            ],
        ),
    ]
