# Generated by Django 3.2.13 on 2022-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0065_alter_to_order_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='To_order',
        ),
    ]
