# Generated by Django 3.2.13 on 2022-12-22 21:48

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0066_delete_to_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricamo.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ricamo.product')),
            ],
        ),
    ]
