# Generated by Django 3.2.13 on 2022-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricamo', '0067_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='selled',
            field=models.BooleanField(default=False),
        ),
    ]
